/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "claves-rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
interfaz_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		struct key_args_in rpc_set_value_1_arg;
		int rpc_get_value_1_arg;
		struct key_args_in rpc_modify_value_1_arg;
		int rpc_delete_key_1_arg;
		int rpc_exist_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case rpc_destroy:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_destroy_1_svc;
		break;

	case rpc_set_value:
		_xdr_argument = (xdrproc_t) xdr_key_args_in;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_set_value_1_svc;
		break;

	case rpc_get_value:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_args_out;
		local = (char *(*)(char *, struct svc_req *)) rpc_get_value_1_svc;
		break;

	case rpc_modify_value:
		_xdr_argument = (xdrproc_t) xdr_key_args_in;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_modify_value_1_svc;
		break;

	case rpc_delete_key:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_delete_key_1_svc;
		break;

	case rpc_exist:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_exist_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (INTERFAZ, FUNCIONESVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, INTERFAZ, FUNCIONESVER, interfaz_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (INTERFAZ, FUNCIONESVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, INTERFAZ, FUNCIONESVER, interfaz_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (INTERFAZ, FUNCIONESVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
