/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVES-RPC_H_RPCGEN
#define _CLAVES-RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct Coord_RPC {
	int x;
	int y;
};
typedef struct Coord_RPC Coord_RPC;

struct args_struct {
	int key;
	char value1[256];
	int N_value2;
	double V_value2[32];
	struct Coord_RPC value3;
	int res;
};
typedef struct args_struct args_struct;

#define INTERFAZ 99
#define FUNCIONESVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define rpc_destroy 1
extern  enum clnt_stat rpc_destroy_1(int *, CLIENT *);
extern  bool_t rpc_destroy_1_svc(int *, struct svc_req *);
#define rpc_set_value 2
extern  enum clnt_stat rpc_set_value_1(args_struct , int *, CLIENT *);
extern  bool_t rpc_set_value_1_svc(args_struct , int *, struct svc_req *);
#define rpc_get_value 3
extern  enum clnt_stat rpc_get_value_1(int , args_struct *, CLIENT *);
extern  bool_t rpc_get_value_1_svc(int , args_struct *, struct svc_req *);
#define rpc_modify_value 4
extern  enum clnt_stat rpc_modify_value_1(args_struct , int *, CLIENT *);
extern  bool_t rpc_modify_value_1_svc(args_struct , int *, struct svc_req *);
#define rpc_delete_key 5
extern  enum clnt_stat rpc_delete_key_1(int , int *, CLIENT *);
extern  bool_t rpc_delete_key_1_svc(int , int *, struct svc_req *);
#define rpc_exist 6
extern  enum clnt_stat rpc_exist_1(int , int *, CLIENT *);
extern  bool_t rpc_exist_1_svc(int , int *, struct svc_req *);
extern int interfaz_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rpc_destroy 1
extern  enum clnt_stat rpc_destroy_1();
extern  bool_t rpc_destroy_1_svc();
#define rpc_set_value 2
extern  enum clnt_stat rpc_set_value_1();
extern  bool_t rpc_set_value_1_svc();
#define rpc_get_value 3
extern  enum clnt_stat rpc_get_value_1();
extern  bool_t rpc_get_value_1_svc();
#define rpc_modify_value 4
extern  enum clnt_stat rpc_modify_value_1();
extern  bool_t rpc_modify_value_1_svc();
#define rpc_delete_key 5
extern  enum clnt_stat rpc_delete_key_1();
extern  bool_t rpc_delete_key_1_svc();
#define rpc_exist 6
extern  enum clnt_stat rpc_exist_1();
extern  bool_t rpc_exist_1_svc();
extern int interfaz_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Coord_RPC (XDR *, Coord_RPC*);
extern  bool_t xdr_args_struct (XDR *, args_struct*);

#else /* K&R C */
extern bool_t xdr_Coord_RPC ();
extern bool_t xdr_args_struct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVES-RPC_H_RPCGEN */
