/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVES-RPC_H_RPCGEN
#define _CLAVES-RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct Coord {
	double x;
	double y;
};
typedef struct Coord Coord;

struct args_in {
	int res;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	struct Coord value3;
};
typedef struct args_in args_in;

struct args_out {
	int res;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	struct Coord value3;
	int status;
};
typedef struct args_out args_out;

struct rpc_set_value_1_argument {
	int key;
	struct args_in arg2;
};
typedef struct rpc_set_value_1_argument rpc_set_value_1_argument;

struct rpc_modify_value_1_argument {
	int key;
	struct args_in arg2;
};
typedef struct rpc_modify_value_1_argument rpc_modify_value_1_argument;

#define INTERFAZ 99
#define FUNCIONESVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define rpc_destroy 1
extern  enum clnt_stat rpc_destroy_1(int *, CLIENT *);
extern  bool_t rpc_destroy_1_svc(int *, struct svc_req *);
#define rpc_set_value 2
extern  enum clnt_stat rpc_set_value_1(int , struct args_in , int *, CLIENT *);
extern  bool_t rpc_set_value_1_svc(int , struct args_in , int *, struct svc_req *);
#define rpc_get_value 3
extern  enum clnt_stat rpc_get_value_1(int , struct args_out *, CLIENT *);
extern  bool_t rpc_get_value_1_svc(int , struct args_out *, struct svc_req *);
#define rpc_modify_value 4
extern  enum clnt_stat rpc_modify_value_1(int , struct args_in , int *, CLIENT *);
extern  bool_t rpc_modify_value_1_svc(int , struct args_in , int *, struct svc_req *);
#define rpc_delete_key 5
extern  enum clnt_stat rpc_delete_key_1(int , int *, CLIENT *);
extern  bool_t rpc_delete_key_1_svc(int , int *, struct svc_req *);
#define rpc_exist 6
extern  enum clnt_stat rpc_exist_1(int , int *, CLIENT *);
extern  bool_t rpc_exist_1_svc(int , int *, struct svc_req *);
extern int interfaz_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rpc_destroy 1
extern  enum clnt_stat rpc_destroy_1();
extern  bool_t rpc_destroy_1_svc();
#define rpc_set_value 2
extern  enum clnt_stat rpc_set_value_1();
extern  bool_t rpc_set_value_1_svc();
#define rpc_get_value 3
extern  enum clnt_stat rpc_get_value_1();
extern  bool_t rpc_get_value_1_svc();
#define rpc_modify_value 4
extern  enum clnt_stat rpc_modify_value_1();
extern  bool_t rpc_modify_value_1_svc();
#define rpc_delete_key 5
extern  enum clnt_stat rpc_delete_key_1();
extern  bool_t rpc_delete_key_1_svc();
#define rpc_exist 6
extern  enum clnt_stat rpc_exist_1();
extern  bool_t rpc_exist_1_svc();
extern int interfaz_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Coord (XDR *, Coord*);
extern  bool_t xdr_args_in (XDR *, args_in*);
extern  bool_t xdr_args_out (XDR *, args_out*);
extern  bool_t xdr_rpc_set_value_1_argument (XDR *, rpc_set_value_1_argument*);
extern  bool_t xdr_rpc_modify_value_1_argument (XDR *, rpc_modify_value_1_argument*);

#else /* K&R C */
extern bool_t xdr_Coord ();
extern bool_t xdr_args_in ();
extern bool_t xdr_args_out ();
extern bool_t xdr_rpc_set_value_1_argument ();
extern bool_t xdr_rpc_modify_value_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVES-RPC_H_RPCGEN */
