/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "claves-rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_rpc_destroy_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_destroy_1_svc(result, rqstp));
}

int
_rpc_set_value_1 (args_struct  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_set_value_1_svc(*argp, result, rqstp));
}

int
_rpc_get_value_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_get_value_1_svc(*argp, result, rqstp));
}

int
_rpc_modify_value_1 (args_struct  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_modify_value_1_svc(*argp, result, rqstp));
}

int
_rpc_delete_key_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_delete_key_1_svc(*argp, result, rqstp));
}

int
_rpc_exist_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_exist_1_svc(*argp, result, rqstp));
}

static void
interfaz_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		args_struct rpc_set_value_1_arg;
		int rpc_get_value_1_arg;
		args_struct rpc_modify_value_1_arg;
		int rpc_delete_key_1_arg;
		int rpc_exist_1_arg;
	} argument;
	union {
		int rpc_destroy_1_res;
		int rpc_set_value_1_res;
		args_struct rpc_get_value_1_res;
		int rpc_modify_value_1_res;
		int rpc_delete_key_1_res;
		int rpc_exist_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case rpc_destroy:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_destroy_1;
		break;

	case rpc_set_value:
		_xdr_argument = (xdrproc_t) xdr_args_struct;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_set_value_1;
		break;

	case rpc_get_value:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_args_struct;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_get_value_1;
		break;

	case rpc_modify_value:
		_xdr_argument = (xdrproc_t) xdr_args_struct;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_modify_value_1;
		break;

	case rpc_delete_key:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_delete_key_1;
		break;

	case rpc_exist:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_exist_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!interfaz_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (INTERFAZ, FUNCIONESVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, INTERFAZ, FUNCIONESVER, interfaz_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (INTERFAZ, FUNCIONESVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, INTERFAZ, FUNCIONESVER, interfaz_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (INTERFAZ, FUNCIONESVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
