/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "claves-rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
rpc_destroy_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_destroy, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_set_value_1(args_struct aux, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_set_value,
		(xdrproc_t) xdr_args_struct, (caddr_t) &aux,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_get_value_1(int key, args_struct *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_get_value,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_args_struct, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_modify_value_1(args_struct aux, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_modify_value,
		(xdrproc_t) xdr_args_struct, (caddr_t) &aux,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_delete_key_1(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_delete_key,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_exist_1(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_exist,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
