/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <dirent.h>
#include <pthread.h>

#include "claves-rpc.h"
#include "mensaje.h"
#include "claves/claves.h"

static pthread_mutex_t m;

int *
rpc_destroy_1_svc(void *arg, struct svc_req *rqstp)
{
    static int result;
    pthread_mutex_lock(&m);
    result = destroy();
    pthread_mutex_unlock(&m);
    return &result;
}

int *
rpc_set_value_1_svc(struct key_args_in *arg, struct svc_req *rqstp)
{
    static int result;
    struct Coord coord;
    coord.x = arg->tupla.value3.x;
    coord.y = arg->tupla.value3.y;

    pthread_mutex_lock(&m);
    result = set_value(arg->key, arg->tupla.value1, arg->tupla.N_value2, arg->tupla.V_value2.V_value2_val, coord);
    pthread_mutex_unlock(&m);
    return &result;
}

struct args_out *
rpc_get_value_1_svc(int *key, struct svc_req *rqstp)
{
    static struct args_out result;
    struct Coord coord;

    pthread_mutex_lock(&m);
    result.res = get_value(*key, result.value1, &result.N_value2, result.V_value2.V_value2_val, &coord);
    pthread_mutex_unlock(&m);

    result.value3.x = coord.x;
    result.value3.y = coord.y;

    return &result;
}

int *
rpc_modify_value_1_svc(struct key_args_in *arg, struct svc_req *rqstp)
{
    static int result;
    struct Coord coord;
    coord.x = arg->tupla.value3.x;
    coord.y = arg->tupla.value3.y;

    pthread_mutex_lock(&m);
    result = modify_value(arg->key, arg->tupla.value1, arg->tupla.N_value2, arg->tupla.V_value2.V_value2_val, coord);
    pthread_mutex_unlock(&m);
    return &result;
}

int *
rpc_delete_key_1_svc(int *key, struct svc_req *rqstp)
{
    static int result;
    pthread_mutex_lock(&m);
    result = delete_key(*key);
    pthread_mutex_unlock(&m);
    return &result;
}

int *
rpc_exist_1_svc(int *key, struct svc_req *rqstp)
{
    static int result;
    pthread_mutex_lock(&m);
    result = exist(*key);
    pthread_mutex_unlock(&m);
    return &result;
}

int
interfaz_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);
	return 1;
}
