/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <dirent.h>

#include "claves-rpc.h"
#include "mensaje.h"
#include "claves/claves.h"

bool_t
rpc_destroy_1_svc(int *result, struct svc_req *rqstp)
{
	bool_t retval;

	*result = destroy();

	return retval;
}

bool_t
rpc_set_value_1_svc(int key, struct args_in arg2, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	*result = set_value(key, arg2.value1, arg2.N_value2, arg2.V_value2, arg2.value3);

	return retval;
}

bool_t
rpc_get_value_1_svc(int key, struct args_out *result,  struct svc_req *rqstp)
{
	bool_t retval;

	result.res = get_value(key, result.value1, &(result.N_value2), result.V_value2, result.value3);

	return retval;
}

bool_t
rpc_modify_value_1_svc(int key, struct args_in arg2, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	*result = modify_value(key, arg2.value1, arg2.N_value2, arg2.V_value2, arg2.value3);

	return retval;
}

bool_t
rpc_delete_key_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	*result = delete_key(key);

	return retval;
}

bool_t
rpc_exist_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	*result = exist(key);

	return retval;
}

int
interfaz_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
